In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as mp
import pandas as pd


In [2]:
obs_sigmas = [0.124, 0.096, 0.154, 0.219]
int_sigmas = [0.040, 0.079, 0.045, 0.057]
phot_sigmas = [0.052, 0.044, 0.046, 0.054]

In [3]:
obs_sigmas = np.array(obs_sigmas)
int_sigmas = np.array(int_sigmas)
phot_sigmas = np.array(phot_sigmas)

In [5]:
metal_sigmas = np.sqrt(obs_sigmas**2 - int_sigmas**2 - phot_sigmas**2)

In [6]:
metal_sigmas

array([ 0.10522357,  0.03223352,  0.13991069,  0.2044407 ])

In [7]:
spect_sigmas = np.array([0.250, 0.132, 0.250, 0.132])
phot_sigmas = np.array([0.254, 0.243, 0.254, 0.243]) 

In [8]:
spec_gammas = metal_sigmas / spect_sigmas
phot_gammas = metal_sigmas / phot_sigmas

In [10]:
spec_gammas

array([ 0.42089429,  0.24419336,  0.55964274,  1.54879319])

In [11]:
metal_sigmas / phot_sigmas

array([ 0.41426603,  0.13264824,  0.55082947,  0.84131975])